# Generated by Django 4.1.13 on 2024-02-12 19:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("asap", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test", models.CharField(max_length=100)),
            ],
        ),
    ]
