# Generated by Django 4.1.13 on 2024-02-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("asap", "0002_test"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("text", models.TextField()),
            ],
        ),
    ]
