# Generated by Django 4.1.13 on 2024-02-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("asap", "0003_post"),
    ]

    operations = [
        migrations.CreateModel(
            name="Version",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=10)),
            ],
        ),
    ]
