# Generated by Django 4.1.13 on 2024-02-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("asap", "0004_version"),
    ]

    operations = [
        migrations.CreateModel(
            name="Test2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=200)),
                ("password", models.CharField(max_length=200)),
                ("email", models.CharField(max_length=200)),
                ("mobile", models.CharField(max_length=200)),
                ("storeName", models.CharField(max_length=200)),
                ("theme", models.CharField(max_length=200)),
                ("purpose", models.CharField(max_length=200)),
                ("resultForm", models.CharField(max_length=200)),
                ("title", models.CharField(max_length=200)),
                ("productName", models.CharField(max_length=200)),
                ("price", models.CharField(max_length=200)),
                ("info", models.CharField(max_length=200)),
                ("time", models.CharField(max_length=200)),
                ("where", models.CharField(max_length=200)),
                ("storePhone", models.CharField(max_length=200)),
            ],
        ),
    ]
