# Generated by Django 4.1.13 on 2024-02-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("asap", "0006_rename_title_test2_loginid_test2_loginpw"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="lae",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="put",
            field=models.TextField(default="default"),
            preserve_default=False,
        ),
    ]
