# Generated by Django 4.1.13 on 2024-02-15 00:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("asap", "0007_post_lae_post_put"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("completed", models.BooleanField(default=False)),
            ],
        ),
    ]
