# Generated by Django 4.1.13 on 2024-02-15 02:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("asap", "0008_task"),
    ]

    operations = [
        migrations.CreateModel(
            name="Img",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("text", models.TextField()),
                ("image", models.ImageField(upload_to="%Y/%m/%d")),
            ],
        ),
    ]
