# Generated by Django 4.1.13 on 2024-02-15 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("asap", "0009_img"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommonInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("store_name", models.CharField(max_length=50)),
                ("purpose", models.CharField(max_length=50)),
                ("result_type", models.CharField(max_length=10)),
                ("theme", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("call_num", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="ItemInfo",
            fields=[
                (
                    "commoninfo_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="asap.commoninfo",
                    ),
                ),
                ("product_name", models.CharField(max_length=50)),
                ("price", models.IntegerField()),
                ("description", models.TextField()),
                ("business_hours", models.CharField(blank=True, max_length=30)),
                ("location", models.CharField(blank=True, max_length=100)),
                ("contact", models.CharField(blank=True, max_length=20)),
            ],
            bases=("asap.commoninfo", models.Model),
        ),
    ]
