# Generated by Django 4.1.13 on 2024-02-15 06:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("asap", "0010_commoninfo_profile_iteminfo"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Profile",
            new_name="User",
        ),
    ]
