# Generated by Django 4.1.13 on 2024-02-15 07:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("asap", "0013_rename_call_num_profile_phone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="name",
        ),
    ]
