# Generated by Django 4.1.13 on 2024-02-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("asap", "0014_remove_profile_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="commoninfo",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
