# Generated by Django 4.1.13 on 2024-02-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("asap", "0015_commoninfo_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_data", models.ImageField(upload_to="chunks/")),
            ],
        ),
    ]
