# Generated by Django 4.1.13 on 2024-02-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("asap", "0016_chunk"),
    ]

    operations = [
        migrations.AddField(
            model_name="chunk",
            name="encoded_image_data",
            field=models.TextField(blank=True, null=True),
        ),
    ]
